Collections:
  - Name: SoftTeacher
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - FPN
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/2106.09018
      Title: "End-to-End Semi-Supervised Object Detection with Soft Teacher"
    README: configs/soft_teacher/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v3.0.0rc1/mmdet/models/detectors/soft_teacher.py#L20
      Version: v3.0.0rc1
